## 2. Create numpy Arrays (1D, 2D, 3D..)

In [3]:
# importing numpy library
import numpy as np

In [6]:
# 1D Numpy Array

arr1 = np.array([1,2,3,45,67])
print(arr1)
print(type(arr1))
print(arr1.dtype)

[ 1  2  3 45 67]
<class 'numpy.ndarray'>
int64


In [9]:
# how to check the dimension of array
print(arr1.ndim)

1


In [21]:
# if different datatypes are given then while converting the given list to 
# numpy array numpy tries to change all the elements in the list to same 
# datatype

arr1 = np.array([1,2,3,4,5,6.7])
print(arr1)
print(type(arr1))

[1.  2.  3.  4.  5.  6.7]
<class 'numpy.ndarray'>


In [24]:
# to check the datatype of numpy array
print(arr1.dtype)

float64


In [26]:
arr1 = np.array([1,2,3,4,'hello',5.5])
print(arr1)
print(type(arr1))
print(arr1.dtype) # U32 : unicode string type with 32 length

['1' '2' '3' '4' 'hello' '5.5']
<class 'numpy.ndarray'>
<U32


In [28]:
# 2D Array

arr2 = np.array([['A','B','C'],['D','E','F']])
arr2

array([['A', 'B', 'C'],
       ['D', 'E', 'F']], dtype='<U1')

In [30]:
print(arr2.ndim)

2


In [31]:
arr2 = np.array([[1,2,3],[4,5,6]])
arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [32]:
arr2.ndim

2

In [34]:
# to find the rows and columns of the array
arr2.shape

(2, 3)

In [35]:
arr3 = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]],[[13,14,15],[16,17,18]]])
arr3

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]])

In [36]:
arr3.ndim

3

In [37]:
arr3.shape

(3, 2, 3)

In [40]:
arr4 = np.array([[[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]],[[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]]])
arr4

array([[[[ 1,  2,  3],
         [ 4,  5,  6]],

        [[ 7,  8,  9],
         [10, 11, 12]]],


       [[[ 1,  2,  3],
         [ 4,  5,  6]],

        [[ 7,  8,  9],
         [10, 11, 12]]]])

In [41]:
arr4.ndim

4

In [42]:
arr4.shape

(2, 2, 2, 3)