## 3. Special Type of Numpy Array

In [4]:
# importing the numpy library
import numpy as np

In [9]:
# Numpy array which is initialized with zero

# 1D zero array
zero_arr = np.zeros(5)
zero_arr

array([0., 0., 0., 0., 0.])

In [6]:
# 2D zero array
zero_arr = np.zeros((2,3))
zero_arr

array([[0., 0., 0.],
       [0., 0., 0.]])

In [7]:
# 3D zero array
zero_arr = np.zeros((2,3,3))
zero_arr 

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [10]:
# create numpy array which is initialized with ones

# 1D ones array
ones_arr = np.ones(6)
ones_arr

array([1., 1., 1., 1., 1., 1.])

In [11]:
# 2D ones array
ones_arr = np.ones((2,2))
ones_arr

array([[1., 1.],
       [1., 1.]])

In [12]:
# 3D ones array
ones_arr = np.ones((2,2,2))
ones_arr

array([[[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]]])

In [13]:
# create a numpy array with a specific value
# full() : this numpy functions helps in creating a numpy array with a specific value

# 1D array filled with 6
array = np.full(5,6)
array

array([6, 6, 6, 6, 6])

In [14]:
# 2D array filled with 9
array = np.full((3,3),9)
array

array([[9, 9, 9],
       [9, 9, 9],
       [9, 9, 9]])

In [16]:
# 3D array filed with 7
array = np.full((2,3,2),7)
array

array([[[7, 7],
        [7, 7],
        [7, 7]],

       [[7, 7],
        [7, 7],
        [7, 7]]])

In [19]:
# identity matrix
# where diagonal elements of the matrix is 1 and other elements are 0

arr = np.eye(5)
arr

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [20]:
# random() package in numpy used for generating random elements

In [21]:
# 1D array of random elements
# rand() : generates random elements between 0 to 1
# rand() function using uniform distribution while selecting the values

np.random.rand(10)

array([0.07762575, 0.8251458 , 0.71978027, 0.56720289, 0.83513215,
       0.68726359, 0.3799335 , 0.21241167, 0.22163926, 0.62267476])

In [22]:
# generate a 2D array of random elements (0 to 1) using rand()

np.random.rand(2,3)

array([[0.58686371, 0.78376246, 0.53077746],
       [0.12367904, 0.47793957, 0.83738084]])

In [23]:
# generate a 3D array of random elements (0 to 1) using rand()

np.random.rand(2,2,3)

array([[[0.4453985 , 0.77829087, 0.97949933],
        [0.15073537, 0.40826181, 0.47831291]],

       [[0.93003334, 0.0983103 , 0.62352809],
        [0.27724332, 0.81621869, 0.93995159]]])

In [24]:
# random() works same as rand()
# difference between rand and random is random accepts only single positional argument or a tuple
# and rand accepts multiple arguments

# 1D array

np.random.random(3)

array([0.92105097, 0.17565839, 0.49100652])

In [26]:
# 2D array

np.random.random((2,3))

array([[0.92171486, 0.85996151, 0.18096143],
       [0.72364619, 0.36390361, 0.00576919]])

In [27]:
# 3D array

np.random.random((2,3,4))

array([[[0.82550392, 0.33843431, 0.17189635, 0.67920779],
        [0.07021516, 0.51987818, 0.09536561, 0.62657204],
        [0.49340571, 0.3504695 , 0.15167874, 0.16488787]],

       [[0.65381978, 0.28814466, 0.83901424, 0.67653961],
        [0.22197049, 0.42446197, 0.13259113, 0.13188483],
        [0.48409332, 0.52055185, 0.28476134, 0.01444811]]])

In [29]:
# randn() : Generates most of the values between -3 to +3
# here n stands for standard Normal distribution (mean = 0, sd = 1)

# 1D Array

np.random.randn(8)

array([ 0.47612802,  0.71265435,  0.10408912,  1.72199311,  0.02053322,
       -0.95372664,  0.25398966,  0.53848128])

In [30]:
# 2D Array

np.random.randn(2,3)

array([[-1.73889399, -0.10199315, -1.16438068],
       [-0.16666244,  0.52053144,  0.22371143]])

In [31]:
# 3D Array

np.random.randn(2,2,3)

array([[[-0.51387855,  1.0273382 ,  0.67312078],
        [-0.96180281, -0.25271957, -0.52515077]],

       [[ 0.30709705, -0.78375367, -0.57230777],
        [-0.97872589,  1.5637139 ,  1.29533229]]])

In [33]:
# randint() : this will generate random integer elements between a range
# randint(start_range, end_range, array_shape)
# 1D Array

rand_int = np.random.randint(10, 100, 5)
rand_int

array([80, 17, 49, 63, 79], dtype=int32)

In [35]:
# 2D Array
rand_int = np.random.randint(10, 100, (2,3))
rand_int

array([[58, 11, 54],
       [15, 49, 42]], dtype=int32)

In [40]:
# 3D Array
rand_int = np.random.randint(10, 20, (2,6,2))
rand_int

array([[[10, 14],
        [18, 19],
        [19, 19],
        [14, 16],
        [13, 16],
        [15, 17]],

       [[13, 17],
        [12, 15],
        [18, 17],
        [15, 17],
        [13, 18],
        [15, 11]]], dtype=int32)

In [54]:
# choice() : works on categorical data
# choice() function is used for selecting random elements from categorical list

ch = np.array(['vinnu','chinnu','binnu','berry'])
np.random.choice(ch, size = 5)

array(['binnu', 'berry', 'vinnu', 'vinnu', 'binnu'], dtype='<U6')

In [55]:
ch = np.array([12.5, 67.9, 34.556, 90.89])
np.random.choice(ch, 6)

array([67.9  , 34.556, 34.556, 34.556, 34.556, 90.89 ])

In [56]:
### ???????
ch = np.array([1,2,3,4,5])
np.random.choice(ch, size = 4)

array([5, 4, 3, 5])

In [57]:
# here replace default value is True means meaning that a value of the list can be selected multiple times.
# replace = False means vice versa of replace = True
np.random.choice(ch, size = 4, replace = False)

array([1, 3, 5, 4])

In [58]:
np.random.choice(ch, size = 10, p = [0.1, 0.3, 0.4, 0.15, 0.05])

array([1, 5, 3, 3, 1, 1, 3, 2, 1, 5])

In [60]:
# generates the random values starting from the seed value
# and generated random values are always same

np.random.seed(42)
np.random.choice(ch, size = 4)

array([4, 5, 3, 5])

In [61]:
# Create Sequence, Shuffle, Permutation, Linearly Spaced

In [62]:
# arrange() : Create sequence of elements

arr1 = np.arange(10,1,-1) # arange(start, end, step)
arr1

array([10,  9,  8,  7,  6,  5,  4,  3,  2])

In [64]:
arr1 = np.arange(1,10,1)
arr1

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [67]:
# shuffle() : used for shuffling data inplace
# any new array is not created the same array is shuffled that is called inplace
# shuffle function rearrange the elements in the original array

np.random.shuffle(arr1)
arr1

array([3, 9, 7, 1, 4, 6, 8, 5, 2])

In [68]:
# permutation() : re_arrange the elements
# permutation() function return a new shuffled array

arr2 = np.random.permutation(arr1)
arr2

array([5, 4, 6, 1, 9, 8, 7, 3, 2])

In [71]:
# linspace(): linearly spaced numpy array
# this generates a special type of numpy array where every two elements have same difference

arr3 = np.linspace(1, 10, 5)
arr3

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])