## 5. Size and Datatype Conversion

In [2]:
# importing numpy library
import numpy as np

In [3]:
songs = np.array(["Monicaaaaaaaaaaaa", "Hukum", "Devara"])
songs

array(['Monicaaaaaaaaaaaa', 'Hukum', 'Devara'], dtype='<U17')

In [4]:
songs.size

3

In [6]:
# U : unicode string of max length 6
print(songs.dtype)

<U17


In [10]:
# astype() : Data type conversion
song_duration = np.array([4.223, 5.4, 100.4])
int_arr = song_duration.astype(int)
int_arr

array([  4,   5, 100])

In [12]:
song_earning = np.array(["500", "300", "5000"])
song_earning.dtype

dtype('<U4')

In [13]:
# string to integer conversion
r1 = song_earning.astype(int)
r1

array([ 500,  300, 5000])

In [14]:
r1.dtype

dtype('int64')

In [15]:
r2 = song_earning.astype(float)
r2

array([ 500.,  300., 5000.])

In [16]:
r2.dtype

dtype('float64')

In [19]:
np.array([True, False, True]).astype(int)

array([1, 0, 1])

In [20]:
np.array([True, False, True]).astype(float)

array([1., 0., 1.])

In [18]:
np.array([1,1,0,1,0,0]).astype(bool)

array([ True,  True, False,  True, False, False])

In [21]:
np.array([12,6,80,-4,0,56,0]).astype(bool)

array([ True,  True,  True,  True, False,  True, False])